include(${CMAKE_SOURCE_DIR}/cmake/AddMachine.cmake)

# EFM family (8/8)
add_subdirectory(EFMBD)
add_subdirectory(EFMSD)
add_subdirectory(EFMXT)
add_subdirectory(EFMCP)
add_subdirectory(EFMRS)
add_subdirectory(EFMCB)
add_subdirectory(EFMHH)
add_subdirectory(EFMCY)

# TRX family (13/13)
add_subdirectory(TRXBD)
add_subdirectory(TRXB2)
add_subdirectory(TRXSD)
add_subdirectory(TRXXT)
add_subdirectory(TRXXC)
add_subdirectory(TRXCP)
add_subdirectory(TRXRS)
add_subdirectory(TRXCB)
add_subdirectory(TRXCH)
add_subdirectory(TRXOH)
add_subdirectory(TRXCY)
add_subdirectory(TRXMA)
add_subdirectory(TRXCL)

# PI family (9/9)
add_subdirectory(PIBD)
add_subdirectory(PISD)
add_subdirectory(PIXT)
add_subdirectory(PIRS)
add_subdirectory(PIML)
add_subdirectory(PIMA)
add_subdirectory(PIHH)
add_subdirectory(PIRC)
add_subdirectory(PICC)
